title: Dropdown
label: Dropdown
status: "ready"
collated: true
context:
    title: "Navigation menu"
    id: "dropdownNavigation"
    items:
      - text: "Item one"
      - text: "Item two"
      - text: "Item three"
        attributes:
          - label: "aria-current"
            value: "page"
      - relatedLinks:
        - text: "Related item one"
        - text: "Related item two"
variants:
  - name: "secondary"
    context:
        title: "Secondary menu"
        id: "dropdownSecondary"
        modifier: "-secondary"
  - name: "right-align"
    context:
        title: "Right-aligned menu"
        id: "dropdownRight"
        class: "rvt-dropdown__menu--right"
  - name: "buttons"
    context:
        title: "Dropdown with buttons"
        id: "dropdownButtons"
        buttons: true
        items:
          - text: "Notify all"
            attributes:
              - label: "role"
                value: "menuitemradio"
          - text: "Notify admins"
            attributes:
              - label: "aria-checked"
                value: "true"
              - label: "role"
                value: "menuitemradio"
          - text: "Notify contributors"
            attributes:
              - label: "role"
                value: "menuitemradio"
          - relatedLinks:
            - text: "Profile settings"
            - text: "Logout"
  - name: "heading"
    context:
        title: "Dropdown with heading"
        id: "dropdownHeading"
        items:
          - text: "Notify all"
            attributes:
              - label: "role"
                value: "menuitemradio"
          - text: "Notify admins"
            attributes:
              - label: "aria-checked"
                value: "true"
              - label: "role"
                value: "menuitemradio"
          - text: "Notify contributors"
            attributes:
              - label: "role"
                value: "menuitemradio"
          - text: "Personal settings"
            relatedLinks:
              - text: "Profile settings"
              - text: "Logout"
  - name: "heading"
    context:
        title: "Heading and buttons"
        id: "dropdownHeadingButtons"
        buttons: true
        items:
          - text: "Notify all"
            attributes:
              - label: "role"
                value: "menuitemradio"
          - text: "Notify admins"
            attributes:
              - label: "aria-checked"
                value: "true"
              - label: "role"
                value: "menuitemradio"
          - text: "Notify contributors"
            attributes:
              - label: "role"
                value: "menuitemradio"
          - text: "Personal settings"
            relatedLinks:
              - text: "Profile settings"
              - text: "Logout"