title: "Row"
status: "ready"
collated: true
context:
  gridItems:
    - content: <span>Single item grid</span>
variants:
  - name: "freshman"
    context:
      classes:
        - sm
      gridItems:
        - content: <span>Small grid</span>
  - name: "sophomore"
    context:
      classes:
        - md
      gridItems:
        - content: <span>Medium size grid</span>
  - name: "junior"
    context:
      classes:
        - lg
      gridItems:
        - content: <span>Large size grid</span>
  - name: "senior"
    context:
      classes:
        - xl
      gridItems:
        - content: <span>XL size grid</span>
  - name: "auto"
    context:
      gridItems:
        - content: <span>Automatic column 1</span>
        - content: <span>Automatic column 2</span>
        - content: <span>Automatic column 3</span>
        - content: <span>Automatic column 4</span>
  - name: "responsive"
    context:
      gridItems:
        - modifier: "-sm"
          content: <span>Responsive automatic column sm</span>
        - modifier: "-md"
          content: <span>Responsive automatic column md</span>
        - modifier: "-lg"
          content: <span>Responsive automatic column lg</span>
        - modifier: "-xl"
          content: <span>Responsive automatic column xl</span>
        - modifier: "-xxl"
          content: <span>Responsive automatic column xxl</span>
  - name: "set"
    context:
      gridItems:
        - modifier: "-4-md"
          content: <span>4 columns medium and up</span>
        - modifier: "-4-md"
          content: <span>4 columns medium and up</span>
        - modifier: "-4-md"
          content: <span>4 columns medium and up</span>
  - name: "mixed"
    context:
      gridItems:
        - content: <span>Automatic column width</span>
        - modifier: "-6-md"
          content: <span>6 columns medium and up</span>
        - content: <span>Automatic column width</span>
  - name: "order"
    context:
      gridItems:
        - modifier: "-4-md"
          content: <span>First column in source</span>
          orders:
            - modifier: "rvt-cols-push-8-md"
        - modifier: "-8-md"
          content: <span>Second column in source</span>
          orders:
            - modifier: "rvt-cols-pull-4-md"
  - name: "right-align"
    context:
      gridItems:
        - modifier: "-4-md"
          content: <span>4 columns medium and up</span>
        - modifier: "-7-md"
          content: <span>7 columns (right-aligned)</span>
          orders:
            - modifier: "rvt-cols--last"
  - name: "loose"
    context:
      gutter: "--loose"
      gridItems:
        - modifier: "-4-md"
          content: <span>Loose gutter</span>
        - modifier: "-4-md"
          content: <span>Loose gutter</span>
        - content: <span>Loose gutter</span>
        - content: <span>Loose gutter</span>
  - name: "tight"
    context:
      gutter: "--tight"
      gridItems:
        - content: <span>Tight gutter</span>
        - content: <span>Tight gutter</span>
        - content: <span>Tight gutter</span>
        - content: <span>Tight gutter</span>
