allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  sharp: true
minimumReleaseAgeExclude:
  - "@changesets/apply-release-plan@8.0.0-next.10"
  - "@changesets/assemble-release-plan@7.0.0-next.10"
  - "@changesets/changelog-git@1.0.0-next.9"
  - "@changesets/cli@3.0.0-next.11"
  - "@changesets/config@4.0.0-next.9"
  - "@changesets/get-dependents-graph@3.0.0-next.9"
  - "@changesets/git@4.0.0-next.9"
  - "@changesets/parse@1.0.0-next.10"
  - "@changesets/pre@3.0.0-next.9"
  - "@changesets/read@1.0.0-next.10"
  - "@changesets/should-skip-package@1.0.0-next.9"
  - "@changesets/types@7.0.0-next.9"
  - "@changesets/write@1.0.0-next.9"
  - "@changesets/changelog-github@1.0.0-next.9"
packages:
  - "packages/*"
saveExact: true
